// Generated by Wrangler on Fri May 17 2024 19:36:49 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  ADMIN_ACCESS_KEY: string;
  RATE_LIMITER: {
    limit: ({ key: string }) => Promise<{ success: boolean }>;
  };
  redirect_limit_store: KVNamespace;
}
