// Generated by Wrangler on Sat May 18 2024 03:12:40 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	SUBGRAPH_ENDPOINT: "https://gateway-arbitrum.network.thegraph.com/api/1df9c80e7e918f669b56b6097dd43f3e/subgraphs/id/DZz4kDTdmzWLWsV373w2bSmoar3umKKH9y82SUKr5qmp";
	API_KEY: string;
	MY_RATE_LIMITER: any;
}
