// Generated by Wrangler on Mon May 13 2024 08:41:07 GMT-1000 (Hawaii-Aleutian Standard Time)
// by running `wrangler types`

interface Env {
	SUBGRAPH_ENDPOINT: "https://gateway-arbitrum.network.thegraph.com/api/subgraphs/id/DZz4kDTdmzWLWsV373w2bSmoar3umKKH9y82SUKr5qmp";
	API_KEY: string;
}
